name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "LICHESS_USERNAME=${{ secrets.LICHESS_USERNAME }}" >> .env
          echo "NUM_GAMES=${{ secrets.NUM_GAMES }}" >> .env
          echo "PERF_TYPE=${{ secrets.PERF_TYPE }}" >> .env
          echo "RUN_AT_TIME=${{ secrets.RUN_AT_TIME }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          echo "DISCORD_DAILY_OPENINGS_TO_SEND=${{ secrets.DISCORD_DAILY_OPENINGS_TO_SEND }}" >> .env

        shell: bash

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/daily-chess
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ENV_FILE=.env

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}
